@startuml Rimozione contatto
title RimuoviContatto
autonumber
actor Utente
participant RubricaView
participant RubricaController
collections Rubrica
Utente -> RubricaView: [clicca icona elimina]
RubricaController -> Rubrica: handleEliminaContatto()
RubricaController -->RubricaView: [aggiorna vista]
@enduml
