@startuml
title Modifica Contatto
autonumber
actor Utente
participant RubricaView
participant RubricaController
collections Rubrica
activate Utente
skinparam sequenceMessageAlign center
Utente->RubricaView: [click su pulsanteModifica]
activate RubricaView
RubricaView->RubricaController:[chiama la handleModificaContatto(OnActioneEvent event)]
activate RubricaController
RubricaController -> Rubrica:handleModificaContatto(OnActioneEvent event)
activate Rubrica
Rubrica --> RubricaController: Ritorna il contatto modificato
deactivate Rubrica
RubricaController -->RubricaView:[aggiorna view]
deactivate RubricaController
deactivate RubricaView
deactivate Utente

@enduml