@startuml
title Aggiungi Contatto
autonumber
actor Utente
participant RubricaView
participant RubricaController
participant CreazioneContattoView
participant CreaContattoController
collections Rubrica

activate Utente
Utente->CreaContattoController: [inserisci informazioni]
Utente->CreaContattoController: [clicca "Crea Contatto"]
activate CreaContattoController
CreazioneContattoView-> CreaContattoController : [invia informazioni sul contatto]
CreaContattoController-> CreaContattoController:  validaCampiObbligatori()
alt [vincoli soddisfatti]
CreaContattoController-> Rubrica : handleAggiungiContatto()
activate Rubrica
else [vincoli non soddisfatti] 
CreaContattoController-->RubricaView: mostraMessaggioErrore()
activate RubricaView
deactivate CreaContattoController
deactivate Rubrica
RubricaView-->Utente: [errore]
end
deactivate RubricaView
deactivate Utente

@enduml
