@startuml
title Aggiungi Contatto
autonumber
actor Utente
participant CreazioneContattoView
participant CreaContattoController
collections Rubrica

activate Utente
Utente->CreazioneContattoView: [inserisci informazioni]
Utente->CreaContattoController: [clicca "Crea Contatto"]
activate CreaContattoController
CreazioneContattoView-> CreaContattoController : [invia informazioni sul contatto]
CreaContattoController-> CreaContattoController:  controllaCampiObbligatori()
CreaContattoController-> CreaContattoController:  controllaTelefono()
CreaContattoController-> CreaContattoController:  controllaEmail()

alt [vincoli soddisfatti]
CreaContattoController-> Rubrica : aggiungiContatto()
activate Rubrica
else [vincoli non soddisfatti] 
CreaContattoController-->Utente: mostraDialog(ERROR)
deactivate CreaContattoController
deactivate Rubrica
end
deactivate Utente

@enduml
