@startuml
title Export
autonumber
actor Utente
participant RubricaView
participant RubricaController
participant Rubrica
participant ExportClass

Utente->RubricaView:[clicca il pulsante condividi]
activate RubricaView
RubricaView->RubricaController:[passa l'evento al suo handler]
deactivate RubricaView
activate RubricaController
RubricaController->Rubrica:getRubrica()
activate Rubrica
Rubrica-->RubricaController:return rubrica.value()
deactivate Rubrica
RubricaController->ExportClass:exportRubrica()
activate ExportClass
ExportClass->ExportClass:esportaRubrica()
ExportClass->ExportClass:[salva il file .vcf]
RubricaController-->RubricaView:mostraOperazioneCompletata()
deactivate ExportClass
activate RubricaView
RubricaView-->Utente:[mostra un alert di conferma]
deactivate RubricaView

@enduml
