@startuml
title Ricerca Contatto
autonumber
actor Utente
participant RubricaView
participant RubricaController
collections Rubrica
activate Utente
Utente -> RubricaView: [Digita nel TextField pulsanteCerca]
activate RubricaView
RubricaView -> RubricaController: chiama filtraContatti(String c)
activate RubricaController
RubricaController -> Rubrica: filtraContatti(String c)
activate Rubrica


opt [(c != null) || (c.trim().isEmpty())]
Rubrica --> RubricaController: Ritorna lista filtrata
deactivate Rubrica
RubricaController --> RubricaView: Aggiorna lista visualizzata
deactivate RubricaController
RubricaView --> Utente: lista aggiornata
end
deactivate RubricaView
deactivate Utente
@enduml
