@startuml DiagrammaClassi
package rubrica {

    package controllers{
       abstract class GenericController{
            - listaContatti: ObservableList<Contatto>
            - rubrica: Rubrica
            + mostraDialog(AlertType, String, String): void
            # controllaCampiObbligatori(String, String) : boolean
            # controllaTelelfono(String) : boolean
            # controllaEmail(String) : boolean

    }

        class RubricaController{
            - contattoSelezionato: Contatto
            - filteredContatti: FilteredList<Contatto>
            - contattiFiltratiPreferiti: FilteredList<Contatto>
            - contattiFiltratiEmergenza: FilteredList<Contatto>
            + initialize(URL, ResourceBundle): void
            + handleNuovoContatto():void
            - filtraContatti(String): void
            - mostraDettaglioContatti(Contatto): void
            - openWebpage(String): void
            - setEditableAll(boolean): void
            + handleEliminaContatto(): void
            + handleModificaContatto(): void
            - gestioneSalvaModifiche():void
            - showRubrica():void
            - showPreferiti():void
            - showEmergenza():void
            - toggleEmergenza():void
            - togglePreferiti(): void
            - openGit():void
            + handleImportRubrica():void
            + handleExportRubrica(): void
            + handleExportContatto(): void
        }
       
        class CreaContattoController {
            +handleAggiungiContatto(ActionEvent): void
        }
    }

        class App {
           - root: Parent
           - scene: Scene
           + start(Stage): void
           + main(String[]): void
        }

    package models{

    class Rubrica{
          - rubrica: Map<Integer, Contatto>
          + aggiungiContatto(Contatto): Contatto
          + ricercaContatto(Contatto): Contatto
          + rimuoviContatto(Contatto): Contatto
          + aggiornaContatto(Contatto, Contatto): Boolean
          + toString(): String

        }
       
  
   abstract class Contatto{
          + Contatto(String, String, String, String, String, Boolean, Boolean):
          - emergenza: Boolean
          - nome: String
          - cognome: String
          - telefono1: String
          - telefono2: String
          - telefono3: String
          - preferito: Boolean
          - id: Integer
          + toString(): String
          + isEmergenza(): BooleanProperty
          + hashCode(): int
          + equals(Object): boolean
          + isPreferito(): BooleanProperty
          # generaId() : Integer       
        }

   class ContattoEsteso {
         + ContattoEsteso(String, String, String, String, String, String, String, 
                     String, LocalDate, String, String, String, Boolean, Boolean)
         - email1: String
         - email2: String
         - email3: String
         - indirizzoResidenza: String
         - sitoWeb: String
         - compleanno: LocalDate
         - note: String
         + toString(): String
         + equals(Object) : boolean
         + hashCode(): int
         # generaId(): Integer
  
        }


    }

  package gestoreIO {

    class Export {
        + getVcard(Contatto): String
        + esportaRubrica(Rubrica, String): void
        + esportaContatto(Contatto, String): void
    }
 
   class Import {
      + importVcard(Rubrica, ObservableList, String): void
}
}
}

Rubrica    "1" o-- "0..*"   Contatto
Contatto     <|--           ContattoEsteso
GenericController  <|--   RubricaController
GenericController  <|--   CreaContattoController
Rubrica -- GenericController
Import -- RubricaController
Export -- RubricaController
App --> RubricaController
