@startuml
package Rubrica {
  class Contatto {
    - String nome
    - String cognome
    - String[] email
    - int[] numero
    - Boolean emergenza
    - Boolean preferiti
    + Contatto(String nome, String cognome, String email, int numero, Boolean emergenza, Boolean preferiti)
    + String getNome()
    + String getCognome()
    + String getEmail()
    + String getNumero()
    + Boolean getEmergenza()
    + Boolean getPreferiti()
    + void setNome(String nome)
    + void setCognome(String cognome)
    + void setEmail(String email)
    + void setNumero(int numero)
    + void setEmergenza(Boolean emergenza)
    + void setPreferiti(Boolean preferiti)
    + Boolean isEmergenza()
    + Boolean isPreferiti()
  }

  class ContattoEsteso {
    - LocalDate compleanno
    - String indirizzoResidenza
    - String socialLinks
    + ContattoEsteso(LocalDate compleanno, String indirizzoResidenza, String socialLinks)
    + LocalDate getCompleanno()
    + String getIndirizzoResidenza()
    + LocalDate setCompleanno(LocalDate compleanno)
    + String setIndirizzoResidenza(String indirizzoResidenza)
    + String setSocialLinks(String socialLinks)
  }

  class Rubrica {
    + void {static} main()
    + Stage start(Stage primaryStage)
  }

  class PreferitiController {
    - ObservableMap preferiti
    + Preferiti()
  }

  class EmergenzeController {
    - ObservableMap emergenze
    + Emergenze()
  }

  class RubricaController {
    - ObservableMap rubrica
    + void aggiungiContatto(Contatto c)
    + void aggiungiContatto(ActionEvent event)
    + Contatto rimuoviContatto(Contatto c)
    + void rimuoviContatto(ActionEvent event)
    + Contatto ricercaContatto(Contatto c)
    + void esportaRubrica()
    + void importaRubrica()
  }

  Contatto <|-- ContattoEsteso
  Rubrica o-- "0..*" Contatto : contiene >
  RubricaController <|-- PreferitiController
  RubricaController <|-- EmergenzeController
  RubricaController *-- Rubrica

  package Eccezioni {
    class ContattoAssenteException{
      + ContattoAssenteException()
    }
    class ContattoDuplicatoException{
      + ContattoDuplicatoException()
    }
    class ExportFileException{
      + ExportFileException()
    }
    class ImportFileException{
      + ImportFileException()
    }

  }
}
@enduml