@startuml RicercaContatto
    title Ricerca Contatto
    autonumber
    actor Utente
    participant RubricaViewController
    collections Rubrica

    activate Utente
    Utente -> RubricaViewController: [Seleziona la casella di ricerca e digita una stringa]
    activate RubricaViewController

    RubricaViewController -> RubricaViewController: filtraContatti()
    activate RubricaViewController #3375E0
    opt stringa != null
    RubricaViewController -> Rubrica : getContatto()
    activate Rubrica
    Rubrica --> RubricaViewController : return listaContatti
    deactivate RubricaViewController
    deactivate Rubrica
    RubricaViewController --> Utente: [Aggiora la TableView]
end
    deactivate Utente
@enduml