@startuml
autonumber
actor Utente
participant RubricaView
participant RubricaController
participant Rubrica
participant Emergenza

activate RubricaView
Utente->RubricaView : Seleziona un contatto dalla lista
activate RubricaController
RubricaView->RubricaController : Richiede la visualizzazione del contatto
activate Rubrica
RubricaController ->Rubrica : Recupera le informazioni del contatto
Rubrica->Rubrica : Fa una get sulla struttura dati
Rubrica->RubricaController : Passa le informazioni
deactivate Rubrica
RubricaController->RubricaView : Aggiorna il binding
deactivate RubricaController
RubricaView->Utente : Mostra il contatto con tutte le informazioni
deactivate RubricaView

Utente->RubricaView : Clicca il pulsante di rimozione dai contatti d'emergenza
activate RubricaView
activate RubricaController
RubricaView->RubricaController : Segnala l'evento di rimozione
RubricaController->RubricaView: Chiama un alert di conferma
RubricaView->Utente: Mostra un alert di conferma

alt [conferma]
    Utente->RubricaView:conferma
    RubricaView->RubricaController: notifica la scelta
    RubricaController->Rubrica : Richiede la rimozione del contatto dai contatti d'emergenza
    activate Emergenza
    Rubrica->Emergenza : Passa l'identificativo del contatto
    Emergenza->Emergenza : Rimuove il contatto dalla lista dei contatti d'emergenza
    Emergenza->Rubrica : Conferma la rimozione
    deactivate Emergenza
    Rubrica->RubricaController : Notifica la rimozione
    RubricaController->RubricaView : Aggiorna il binding e torna alla home
    RubricaView->Utente : Mostra la home aggiornata con il contatto rimosso dai contatti d'emergenza
else [non conferma]
    Utente->RubricaView:non conferma
    RubricaView->RubricaController: notifica la scelta
    RubricaController->RubricaView: Aggiorna il binding e torna alla home
    RubricaView->Utente: mostra la home invariata
    deactivate RubricaController
    deactivate RubricaView
end

@enduml