@startuml Rimozione contatto
autonumber
actor Utente
participant RubricaView
participant RubricaController
participant Rubrica
Utente -> RubricaView: [seleziona icona elimina]
RubricaView --> Utente: [mostra lista contatti da eliminare]
Utente -> RubricaView: [seleziona contatto da eliminare]
RubricaView -> RubricaController: [rimuovi contatto selezionato]
RubricaController -> Rubrica: [rimuovi contatto]
Rubrica -> Rubrica: [elimina]
Rubrica --> RubricaView: [aggiorna lista]
RubricaView --> Utente: [contatto eliminato]
@enduml
