@startuml
'https://plantuml.com/sequence-diagram

actor Utente

Utente -> RubricaView : Seleziona la casella di ricerca e digita una stringa
RubricaView -> RubricaController : Passa la stringa al controller
RubricaController -> Rubrica : Cerca la stringa nella struttura dati

alt Stringa presente
    Rubrica -> RubricaController : Restituisce i dati del contatto corrispondente
    RubricaController -> RubricaView : Aggiorna il binding con i dati
    RubricaView -> Utente : Mostra il contatto a video
else Stringa non presente
    Rubrica -> RubricaController : Restituisce uno statusCode di errore
    RubricaController -> RubricaView : Notifica l'errore
    RubricaView -> Utente : Mostra un alert con il messaggio di errore
end
@enduml