@startuml Rimozione contatto
title RimuoviContatto
autonumber
actor Utente
activate Utente
participant RubricaView
participant RubricaController
collections Rubrica
activate RubricaView
Utente -> RubricaView: [clicca icona elimina]
RubricaView <-> RubricaController : [comunicazione]
activate RubricaController
activate RubricaController #3375E0
RubricaController -> RubricaController: handleEliminaContatto()
activate Rubrica
RubricaController -> Rubrica : RimuoviContatto()
deactivate Rubrica
deactivate RubricaView
deactivate RubricaController
deactivate RubricaController
deactivate Utente
@enduml
