@startuml
title Importa Rubrica
autonumber
actor Utente
participant RubricaView
participant RubricaController
collections Rubrica

activate Utente
activate RubricaView
Utente->RubricaView:[clicca sulla toolbar il tasto "file -> Import"]
activate RubricaController
RubricaController<->RubricaView:[comunicazione]
deactivate RubricaView
RubricaController-->Utente:[Mostra la schermata di importazione]
deactivate RubricaController

alt [Conferma]
    activate RubricaView
    Utente->RubricaView:[Conferma di voler importare]
    activate RubricaController
    RubricaView<->RubricaController:[comunicazione]
    RubricaController->RubricaController : handleImportRubrica()
    deactivate RubricaView
    activate RubricaController #3375E0
    RubricaController->RubricaController : importVCard()
    activate RubricaController #3375E0
    activate Rubrica
    RubricaController->Rubrica : aggiungiContatto()
    deactivate Rubrica
    alt [import success]
        RubricaController-->Utente: mostraDialog(SUCCESS)
    else #pink [import fail] 
        RubricaController-->Utente: mostraDialog(ERROR)
    end
    deactivate RubricaController
    deactivate RubricaController
    deactivate Rubrica
    deactivate RubricaController
    activate RubricaView
else #pink [annulla]
    Utente->RubricaView:[click "annulla"]
    activate RubricaController
    RubricaView<->RubricaController:[comunicazione]
    deactivate RubricaController
    RubricaController-->Utente:[torna nella home]
end
deactivate RubricaView

@enduml
