@startuml
title Modifica Contatto
autonumber
actor Utente
participant RubricaView
participant RubricaController
collections Rubrica
activate Utente
skinparam sequenceMessageAlign center
Utente->RubricaView: [click su pulsanteModifica]
activate RubricaView
RubricaView->RubricaController: [OnActionEvent event generato da pulsanteModifica]
activate RubricaController
RubricaController -> RubricaController:handleModificaContatto(OnActioneEvent event)
activate RubricaController
deactivate RubricaController
RubricaController->Rubrica: aggiornaContatto()
deactivate RubricaController
activate Rubrica
deactivate Rubrica
RubricaView->Utente:[view aggiornata]
deactivate RubricaView
deactivate Utente

@enduml
