@startuml
'https://plantuml.com/sequence-diagram
autonumber
actor Utente

Utente->RubricaView : [Seleziona un contatto dalla lista]
activate RubricaView
RubricaView->RubricaController : [Richiede la visualizzazione del contatto]
activate RubricaController
RubricaController->Rubrica : [Recupera le informazioni del contatto]
activate Rubrica
Rubrica->Rubrica: get()
Rubrica-->RubricaController : [Passa le informazioni]
deactivate Rubrica
RubricaController-->RubricaView : [Aggiorna il binding]
deactivate RubricaController
RubricaView-->Utente : [Mostra il contatto con tutte le informazioni]
deactivate RubricaView
Utente->RubricaView : [Clicca il tasto "Aggiungi ai preferiti"]
activate RubricaView
RubricaView->RubricaController : [Segnala l'evento di click]
activate RubricaController
RubricaController->Rubrica : [Aggiunge il contatto ai preferiti]
activate Rubrica
Rubrica->Preferiti : [Passa le informazioni del contatto]
activate Preferiti
Preferiti->Preferiti : add()
deactivate Rubrica
Preferiti-->RubricaController : [Notifica l'aggiunta]
deactivate Preferiti
RubricaController-->RubricaView : [Aggiorna il binding]
deactivate RubricaController
RubricaView-->Utente : [Mostra l'icona dei preferiti aggiornata]
deactivate RubricaView
@enduml