@startuml Aggiunta contatto
autonumber
actor Utente
Utente -> RubricaView : [seleziona icona creaContatto]
RubricaView-->Utente: [mostra campi da compilare]
Utente->RubricaView: [aggiunge informazioni contatto]
RubricaView->RubricaController: [invia informazioni da salvare]
RubricaController->RubricaController: [controllo contatto soddisfa vincoli]
alt [vincoli soddisfatti]
RubricaController->Rubrica: [richiesta di aggiunta]
Rubrica->Rubrica: add()
Rubrica-->RubricaView: [aggiorna rubrica]
RubricaView-->Utente: [mostra lista aggiornata]
 else [vincoli non soddisfatti]
RubricaController-->RubricaView: throw new VincoliException()
RubricaView-->Utente: [errore]
end
@enduml