@startuml
    title "Diagramma dei package"
    set separator none
    package it.unisa.diem.swe.group07.rubrica {
        package controllers{}
        package models {}
        package tests {}
        package eccezioni {}
        package gestoreIO {}
@enduml
