@startuml DPackage
    title "Diagramma dei package"
    set separator none
    package it.unisa.diem.swe.group07{
      package rubrica {
          package controllers{}
          package models {}
          package gestoreIO {}
      }
    }
@enduml
