//bozza di prova probabilmente piena di errori
@startuml
actor Utente
Utente -> RubricaView :seleziona la barra di ricerca
RubricaView -> RubricaController : ricerca(nome, cognome)
RubricaController -> Rubrica : get(nome, cognome)
Rubrica -> RubricaController : restituisce contatto
RubricaController -> RubricaView : mostra a schermo
RubricaView -> Utente : vede il contatto


Utente -> RubricaView:clicca file sulla toolbar
RubricaView -> RubricaController:binding
RubricaController->RubricaView:binding
RubricaView->Utente:mostra il nuovo menu a video
Utente->RubricaView:seleziona export
RubricaView->RubricaController:binding
RubricaController->Rubrica:chiama export()
Rubrica->RubricaController:return status code
RubricaController->RubricaView:binding
RubricaView->Utente:mostra esito

Utente -> RubricaView:clicca file sulla toolbar
RubricaView -> RubricaController:binding
RubricaController->RubricaView:binding
RubricaView->Utente:mostra il nuovo menu a video
Utente->RubricaView:seleziona import
RubricaView->RubricaController:binding
RubricaController->Rubrica:chiama import()
Rubrica->RubricaController:chide un file
RubricaController->RubricaView:binding
RubricaView->Utente:richiede nome file
Utente->RubricaView:input filename
RubricaView->RubricaController:binding
Rubrica->RubricaController:return status code
RubricaController->RubricaView:binding
RubricaView->Utente:mostra la home con la rubrica importata o errore

@enduml